function Hd = design_hp_filter
%DESIGN_HP_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 11-Mar-2026 13:40:43

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N     = 500;  % Order
Fstop = 0.1;  % Stopband Frequency
Fpass = 0.5;  % Passband Frequency
Wstop = 1;    % Stopband Weight
Wpass = 1;    % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);
Hd = dfilt.dffir(b);

% [EOF]
