function Hd = design_lp_filter
%DESIGN_LP_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 11-Mar-2026 13:34:28

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N    = 200;      % Order
Fc   = 90;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
